create table car (
       car_id integer generated by default as identity (start with 1),
        doors integer,
        drive_train varchar(100),
        engine varchar(100),
        make varchar(100) not null,
        mileage integer not null,
        model varchar(100) not null,
        modification varchar(255),
        transmission varchar(100),
        vin_number varchar(255),
        car_year integer not null,
        color_id integer not null,
        primary key (car_id)
    )

    create table car_color (
       color_id integer generated by default as identity (start with 1),
        color_name varchar(255) not null,
        primary key (color_id)
    )

    create table car_image (
       image_id integer generated by default as identity (start with 1),
        image_path varchar(255),
        id_car_item integer,
        primary key (image_id)
    )

    create table car_item (
       car_item_id integer generated by default as identity (start with 1),
        address_locality varchar(255) not null,
        create_item timestamp not null,
        description varchar(255),
        price integer not null,
        sold boolean not null,
        id_car integer not null,
        id_person integer not null,
        primary key (car_item_id)
    )

    create table person (
       person_id integer generated by default as identity (start with 1),
        create_user_date date not null,
        email varchar(100) not null,
        first_name varchar(100) not null,
        login varchar(100) not null,
        password varchar(100) not null,
        phone_number varchar(20) not null,
        primary key (person_id)
    )


    alter table car_color
       add constraint UK_t4j9p4pwhrpp7gqj72mydcu0v unique (color_name)


    alter table person
       add constraint UK_3tnwg2lomhbqckauuc1997bx7 unique (login)


    alter table car
       add constraint FKphabaed433w73081v4t2jk6uu
       foreign key (color_id)
       references car_color

    alter table car_image
       add constraint FKakaia13gx48fywtsm4yja8ip1
       foreign key (id_car_item)
       references car_item


    alter table car_item
       add constraint FKc7ot0q8q6j6mf5qttxa4euboh
       foreign key (id_car)
       references car


    alter table car_item
       add constraint FKaqq0rk7petgexgceltj5al6q3
       foreign key (id_person)
       references person


    alter table car_item
       add constraint FK6l7sj5ysdnmub22yiexq9xxpq
       foreign key (car_item_id)
       references person
